
#ifndef INFER_FLOW_NAMESPACE
#   define INFER_FLOW_NAMESPACE
#   define INFER_FLOW_BEGIN namespace inferflow {
#   define inferflow_begin namespace inferflow {
#   define INFER_FLOW_END }
#   define inferflow_end }
#   define USE_INFER_FLOW using namespace inferflow
#   define use_inferflow using namespace inferflow

#   define TRANSFORMER_BEGIN namespace transformer {
#   define transformer_begin namespace transformer {
#   define TRANSFORMER_END }
#   define transformer_end }
#   define USE_TRANSFORMER using namespace inferflow::transformer
#   define use_transformer using namespace inferflow::transformer
#endif //ifndef

